export interface MedicationUomMaster {
  unit_of_measure: string;
  description: string;
}

export interface MedicationRouteMaster {
  route_code: string;
  route_description: string;
}

export interface MedicationFrequencyMaster {
  dosage_no: string;
  dosage_freq: string | null;
  dosage_desc: string;
  arrangement_count: number;
  priority_order: number;
}

export const MEDICATION_UOM_MASTERS: MedicationUomMaster[] = [
  { unit_of_measure: '250ML', description: '250ML' },
  { unit_of_measure: '400G', description: '400GRAMS' },
  { unit_of_measure: '5ML', description: '5 milliliters' },
  { unit_of_measure: 'A', description: 'Ampere' },
  { unit_of_measure: 'AMP', description: 'AMPULE' },
  { unit_of_measure: 'B120', description: 'BOX120' },
  { unit_of_measure: 'BAG', description: 'Bag' },
  { unit_of_measure: 'BAR', description: 'bar' },
  { unit_of_measure: 'BOOK', description: 'Booklet' },
  { unit_of_measure: 'BOT', description: 'bottle' },
  { unit_of_measure: 'BOT10', description: '1' },
  { unit_of_measure: 'BOT120', description: '120' },
  { unit_of_measure: 'BOX', description: 'BOX' },
  { unit_of_measure: 'BOX10', description: 'BOX10' },
  { unit_of_measure: 'BOX12', description: '12' },
  { unit_of_measure: 'BOX150', description: '150' },
  { unit_of_measure: 'BOX2', description: '1' },
  { unit_of_measure: 'BOX25', description: '25' },
  { unit_of_measure: 'BOX30', description: '30 TAB' },
  { unit_of_measure: 'BOX32', description: 'BOX32' },
  { unit_of_measure: 'BOX5', description: '5' },
  { unit_of_measure: 'BOX7', description: '7' },
  { unit_of_measure: 'BOX90', description: '90' },
  { unit_of_measure: 'BT10', description: 'Bottle 10' },
  { unit_of_measure: 'BT30', description: 'BOT30' },
  { unit_of_measure: 'BX', description: '100' },
  { unit_of_measure: 'BX10', description: 'BOX10' },
  { unit_of_measure: 'BX12', description: 'BOX12' },
  { unit_of_measure: 'BX15', description: 'BOX15' },
  { unit_of_measure: 'BX21', description: 'BOX21' },
  { unit_of_measure: 'BX28', description: 'BOX28' },
  { unit_of_measure: 'BX30', description: 'BOX30' },
  { unit_of_measure: 'BX32', description: '1' },
  { unit_of_measure: 'BX40', description: 'BOX40' },
  { unit_of_measure: 'CAL', description: 'calorie' },
  { unit_of_measure: 'CAN', description: 'can' },
  { unit_of_measure: 'CAP', description: 'capsule' },
  { unit_of_measure: 'CART', description: 'catridge' },
  { unit_of_measure: 'CC', description: 'cubic centimeter' },
  { unit_of_measure: 'CLIP', description: 'CLIP' },
  { unit_of_measure: 'CUM', description: 'CUBIC MTR' },
  { unit_of_measure: 'CYCLE', description: 'CYCLE' },
  { unit_of_measure: 'DAY', description: 'day' },
  { unit_of_measure: 'DISK', description: 'disk' },
  { unit_of_measure: 'DOZ', description: 'dozen' },
  { unit_of_measure: 'EA', description: 'each' },
  { unit_of_measure: 'EACH', description: 'each' },
  { unit_of_measure: 'FEE', description: 'fee' },
  { unit_of_measure: 'FEET', description: 'feet' },
  { unit_of_measure: 'FT', description: 'FOOT' },
  { unit_of_measure: 'GAL', description: 'gallon' },
  { unit_of_measure: 'GM20', description: 'GRAM 20' },
  { unit_of_measure: 'GM50', description: 'GRAM 50' },
  { unit_of_measure: 'GRAM', description: 'gram' },
  { unit_of_measure: 'GRAM20', description: '20 GRAMS' },
  { unit_of_measure: 'GRAM50', description: '50 GRAMS' },
  { unit_of_measure: 'HOUR', description: 'hour' },
  { unit_of_measure: 'HR', description: 'hour' },
  { unit_of_measure: 'I', description: '' },
  { unit_of_measure: 'INCH', description: 'INCH' },
  { unit_of_measure: 'INJ', description: 'injection' },
  { unit_of_measure: 'INST', description: 'instrument' },
  { unit_of_measure: 'JAR', description: 'jar' },
  { unit_of_measure: 'KILO', description: 'kilogram' },
  { unit_of_measure: 'KIT', description: 'kit' },
  { unit_of_measure: 'LOZ', description: 'lozenge' },
  { unit_of_measure: 'LPM', description: 'L/Min' },
  { unit_of_measure: 'LTR', description: 'liter' },
  { unit_of_measure: 'MG', description: 'milligram' },
  { unit_of_measure: 'MIN', description: 'minute' },
  { unit_of_measure: 'ML', description: 'milliliter' },
  { unit_of_measure: 'MTR', description: 'meter' },
  { unit_of_measure: 'NEB', description: 'nebule' },
  { unit_of_measure: 'OVUL', description: 'ovule' },
  { unit_of_measure: 'PACK', description: 'Pack' },
  { unit_of_measure: 'PACK2', description: 'Pack2' },
  { unit_of_measure: 'PAD', description: 'pad' },
  { unit_of_measure: 'PAIR', description: 'pair' },
  { unit_of_measure: 'PANEL', description: 'PANEL' },
  { unit_of_measure: 'PATC', description: 'patc' },
  { unit_of_measure: 'PATCH', description: 'PATCH' },
  { unit_of_measure: 'PC', description: 'piece' },
  { unit_of_measure: 'PCS', description: 'pieces' },
  { unit_of_measure: 'PCTH', description: 'pcth' },
  { unit_of_measure: 'PFEE', description: 'pfee' },
  { unit_of_measure: 'PFS', description: 'pre-filled syringe' },
  { unit_of_measure: 'PKS', description: 'packs' },
  { unit_of_measure: 'POLY', description: 'polyampule' },
  { unit_of_measure: 'PROC', description: 'procedure' },
  { unit_of_measure: 'PSI', description: 'LBS/IN2' },
  { unit_of_measure: 'PTCH', description: 'patch' },
  { unit_of_measure: 'PUL', description: 'pul' },
  { unit_of_measure: 'REAM', description: 'ream' },
  { unit_of_measure: 'RESP', description: 'resp' },
  { unit_of_measure: 'ROLL', description: 'roll' },
  { unit_of_measure: 'ROOM', description: 'room' },
  { unit_of_measure: 'SACH', description: 'sachet' },
  { unit_of_measure: 'SET', description: 'set' },
  { unit_of_measure: 'SHFT', description: 'shift' },
  { unit_of_measure: 'SHOT', description: 'shot' },
  { unit_of_measure: 'SHT', description: 'sheet' },
  { unit_of_measure: 'STR5', description: 'STRIPS 5' },
  { unit_of_measure: 'STRIP5', description: '1' },
  { unit_of_measure: 'STRP', description: 'STRIP' },
  { unit_of_measure: 'SUPP', description: 'supply' },
  { unit_of_measure: 'SYR', description: 'syrup' },
  { unit_of_measure: 'TAB', description: 'tablet' },
  { unit_of_measure: 'TANK', description: 'Tank' },
  { unit_of_measure: 'TEST', description: 'TEST' },
  { unit_of_measure: 'TIN', description: 'tin' },
  { unit_of_measure: 'TRAY', description: 'tray' },
  { unit_of_measure: 'TRAY100', description: '' },
  { unit_of_measure: 'TUBE', description: 'tube' },
  { unit_of_measure: 'UNIT', description: 'unit' },
  { unit_of_measure: 'USE', description: 'use' },
  { unit_of_measure: 'VA', description: 'Volt-Amper' },
  { unit_of_measure: 'VIAL', description: 'VIAL' },
  { unit_of_measure: 'VOLTS', description: 'Voltage' },
  { unit_of_measure: 'YARD', description: 'yard' }
];

export const MEDICATION_ROUTE_MASTERS: MedicationRouteMaster[] = [
  { route_code: 'BRZ', route_description: 'VIA BREEZHALER' },
  { route_code: 'CVX', route_description: 'PER CERVIX' },
  { route_code: 'EARS', route_description: 'EACH EAR' },
  { route_code: 'ENOS', route_description: 'EACH NOSTRIL' },
  { route_code: 'EPI', route_description: 'EPIDURAL' },
  { route_code: 'ET TUBE', route_description: 'VIA ENDOTRACHEAL (ET) TUBE' },
  { route_code: 'GT', route_description: 'PER GASTROSTOMY' },
  { route_code: 'HND', route_description: 'VIA HANDIHALER' },
  { route_code: 'IA', route_description: 'INTRA-ARTERIAL' },
  { route_code: 'ID', route_description: 'INTRADERMAL (ID)' },
  { route_code: 'IM', route_description: 'INTRAMUSCULAR (IM)' },
  { route_code: 'IN PUMP', route_description: 'VIA INFUSION PUMP' },
  { route_code: 'IP', route_description: 'INTRAPERITONEAL' },
  { route_code: 'IT', route_description: 'INTRATHECAL' },
  { route_code: 'ITC', route_description: 'INTRATHORACIC' },
  { route_code: 'IV', route_description: 'INTRAVENOUS (IV)' },
  { route_code: 'IV IN', route_description: 'INTRAVENOUS INFUSION (IVIN)' },
  { route_code: 'IVB', route_description: 'INTRAVENOUS BOLUS (IVB)' },
  { route_code: 'IVD', route_description: 'INTRAVENOUS DRIP (IVD)' },
  { route_code: 'IVP', route_description: 'INTRAVENOUS PUSH (IVP)' },
  { route_code: 'IVTT', route_description: 'INTRAVENOUS THROUGH TUBING (IVTT)' },
  { route_code: 'JEJ', route_description: 'PER JEJUNOSTOMY' },
  { route_code: 'NEB', route_description: 'NEBULIZATION' },
  { route_code: 'NGT', route_description: 'NASOGASTRIC TUBE (NGT/GT)' },
  { route_code: 'NOS', route_description: 'PER NOSTRIL' },
  { route_code: 'OD', route_description: 'RIGHT EYE' },
  { route_code: 'OGT', route_description: 'PER OROGASTRIC TUBE (OGT)' },
  { route_code: 'OPTH', route_description: 'OPHTHALMIC' },
  { route_code: 'OS', route_description: 'LEFT EYE' },
  { route_code: 'OU', route_description: 'EACH EYE' },
  { route_code: 'PEG', route_description: 'PERCUTANEOUS ENDOSCOPIC GASTROSTOMY (PEG)' },
  { route_code: 'PO', route_description: 'ORAL (PO)' },
  { route_code: 'PR', route_description: 'PER RECTUM (PR)' },
  { route_code: 'PUF', route_description: 'PUFF' },
  { route_code: 'SL', route_description: 'SUBLINGUAL (SL)' },
  { route_code: 'SST', route_description: 'SINGLE-SYRINGE TECHNIQUE (SST)' },
  { route_code: 'SUBCUT', route_description: 'SUBCUTANEOUS (SQ)' },
  { route_code: 'TOP', route_description: 'TOPICAL' },
  { route_code: 'VAG', route_description: 'PER VAGINA' },
  { route_code: 'EARR', route_description: 'RIGHT EAR' },
  { route_code: 'EARL', route_description: 'LEFT EAR' },
  { route_code: 'BUCC', route_description: 'BUCCAL' },
  { route_code: 'FACEM-NEB', route_description: 'FACEMASK NEBULIZATION' },
  { route_code: 'GAR', route_description: 'GARGLE' },
  { route_code: 'IHD', route_description: 'INTRADIALYTIC' },
  { route_code: 'IJ', route_description: 'VIA INTRAJUGULAR CATH (IJ)' },
  { route_code: 'IO', route_description: 'INTRAOSSEOUS' },
  { route_code: 'MUCTHR', route_description: 'MUCOSAL-THROAT' },
  { route_code: 'OCARE', route_description: 'ORAL CARE' },
  { route_code: 'OINH', route_description: 'ORAL INHALATION' },
  { route_code: 'PER', route_description: 'PER PERINEUM' },
  { route_code: 'PICC', route_description: 'CENTRAL LINE' },
  { route_code: 'RESPC', route_description: 'VIA RESPICHAMBER' },
  { route_code: 'SW', route_description: 'SWISH AND SWALLOW' },
  { route_code: 'TRANSD', route_description: 'TRANSDERMALLY' },
  { route_code: 'URT', route_description: 'INTRAURETHRAL (IU)' },
  { route_code: 'VES', route_description: 'INTRAVESICULAR' },
  { route_code: 'IPL', route_description: 'INTRAPLEURAL' }
];

export const MEDICATION_FREQUENCY_MASTERS: MedicationFrequencyMaster[] = [
  { dosage_no: '1', dosage_freq: '1', dosage_desc: 'once a day', arrangement_count: 14, priority_order: 1 },
  { dosage_no: '10', dosage_freq: '3', dosage_desc: 'every 8 hours', arrangement_count: 8, priority_order: 1 },
  { dosage_no: '11', dosage_freq: '2', dosage_desc: 'every 12 hours', arrangement_count: 7, priority_order: 1 },
  { dosage_no: '12', dosage_freq: '1', dosage_desc: 'every 24 hours', arrangement_count: 6, priority_order: 1 },
  { dosage_no: '13', dosage_freq: '0', dosage_desc: '---', arrangement_count: 1, priority_order: 3 },
  { dosage_no: '14', dosage_freq: '1', dosage_desc: 'Now', arrangement_count: 3, priority_order: 3 },
  { dosage_no: '2', dosage_freq: '2', dosage_desc: 'twice a day', arrangement_count: 16, priority_order: 1 },
  { dosage_no: '3', dosage_freq: '3', dosage_desc: 'thrice a day', arrangement_count: 17, priority_order: 1 },
  { dosage_no: '4', dosage_freq: '4', dosage_desc: '4 times/day', arrangement_count: 18, priority_order: 1 },
  { dosage_no: '5', dosage_freq: '5', dosage_desc: '5 times/day', arrangement_count: 19, priority_order: 1 },
  { dosage_no: '6', dosage_freq: '12', dosage_desc: 'every 2 hours', arrangement_count: 12, priority_order: 1 },
  { dosage_no: '7', dosage_freq: '8', dosage_desc: 'every 3 hours', arrangement_count: 11, priority_order: 1 },
  { dosage_no: '8', dosage_freq: '6', dosage_desc: 'every 4 hours', arrangement_count: 10, priority_order: 1 },
  { dosage_no: '9', dosage_freq: '4', dosage_desc: 'every 6 hours', arrangement_count: 9, priority_order: 1 },
  { dosage_no: '15', dosage_freq: '1', dosage_desc: 'once a day, hours of sleep', arrangement_count: 15, priority_order: 1 },
  { dosage_no: '16', dosage_freq: '1', dosage_desc: 'STAT', arrangement_count: 2, priority_order: 2 },
  { dosage_no: '17', dosage_freq: '1', dosage_desc: 'every 72 hours', arrangement_count: 4, priority_order: 1 },
  { dosage_no: '18', dosage_freq: '1', dosage_desc: 'every 48 hours', arrangement_count: 5, priority_order: 1 },
  { dosage_no: '19', dosage_freq: '1', dosage_desc: 'every other day', arrangement_count: 13, priority_order: 1 },
  { dosage_no: '20', dosage_freq: '1', dosage_desc: 'once a week', arrangement_count: 20, priority_order: 1 },
  { dosage_no: '21', dosage_freq: '1', dosage_desc: 'twice a week', arrangement_count: 21, priority_order: 1 },
  { dosage_no: '22', dosage_freq: '1', dosage_desc: 'thrice a week', arrangement_count: 22, priority_order: 1 },
  { dosage_no: '23', dosage_freq: null, dosage_desc: '--', arrangement_count: 23, priority_order: 1 }
];
